name: Finbarr Timbers
description: Personal website for Finbarr Timbers
url: "http://finbarr.ca"

# Author info
author_name: Finbarr Timbers
author_image_path: /images/finbarr-and-candace.jpg
author_bio: |
    Grad student at <a href=http://www.lse.ac.uk/>LSE</a>.<br>
    Hacker, actor. <br>
    

# External services
about_url: "http://finbarr.ca/about/"
github_url: "https://github.com/timbers"
twitter_url: "https://twitter.com/finbarrtimbers"
linkedin_url: "http://www.linkedin.com/profile/view?id=129265392"
email: "ft+site@finbarr.ca"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /:title/
relative_permalinks: false
pygments: true

