name: Finbarr Timbers
description: Personal website for Finbarr Timbers
url: "http://finbarr.ca"

# Author info
author_name: Finbarr Timbers
author_image_path: /images/finbarr-and-candace.jpg
author_bio: |
  ML Engineer/Data Scientist at [Darkhorse Analytics](http://www.dha.io)

# Projects
projects:
 - name: www.BugDedupe.com
   url: http://www.bugdedupe.com
   description: |
     I turned my academic research into a SaaS app that automatically analysed &
     deduplicate bug reports. Unfortunately, it was too expensive for me to
     keep running, but I have the code & can deploy it with a few hours work.

     If anyone's interested in using this at their company, I'd love to talk to
     you.

 - name: Automated textual analysis for bug report deduplication
   url: /dedup/
   description: "A system that automatically detects duplicate bug reports."

# Talks
talks:
 - name: "A talker on Docker: How containers can make your work more reproducible, accessible, and ready for production"
   conference: "[Edmonton Data Science Meetup](http://www.meetup.com/startupedmonton/events/231589029/). Edmonton, AB, October 5th, 2016."
   slides: "Slides: [PDF](http://finbarr.ca/slides/docker-demo.pdf)."

 - name: "Automating your work away: One consulting firm's experience using KnitR"
   conference: "[UseR! 2016](http://www.user2016.org), [Stanford University](http://www.Stanford.edu), Stanford, CA, Tuesday, June 28th, 2016."
   slides: "Slides: [HTML](http://finbarr.ca/slides/useR-2016.html#1), [PDF](http://finbarr.ca/slides/useR-2016.pdf), [Video](https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/Automating-our-work-away-One-consulting-firms-experience-with-KnitR)."

# work experience
jobs:
  - employer: Darkhorse Analytics
    url: http://dha.io
    title: "ML Engineer/Data Scientist"
    description: |
      Used my background in academic research to come up with highly
      scalable algorithms based on machine learning to solve our clients
      needs. Solutions were typically based on the state of the art academic
      literature.



# External services
about_url: "http://finbarr.ca/about/"
github_url: "https://github.com/finblarr"
twitter_url: "https://twitter.com/finblarr"
linkedin_url: "http://www.linkedin.com/profile/view?id=129265392"
email: "finbarrtimbers@gmail.com"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /:title/
relative_permalinks: false
