name: Finbarr Timbers
description: Personal website for Finbarr Timbers
url: "http://finbarr.ca"

# Author info
author_name: Finbarr Timbers
author_image_path: /images/finbarr-and-candace.jpg
author_bio: |

# Projects
projects:
 - name: Bug Deduplication
   description: A system that automatically detects duplicate bug reports in OSS projects.
   url: https://github.com/tannner/dedup

 - name: Incanter
   description: Statistical-computing & graphics environment for the JVM (contributor).
   url: https://github.com/incanter/incanter

 - name: Cascalog
   description: Data processing and querying library for Clojure (contributor).
   url: https://github.com/nathanmarz/cascalog

# past gigs
gigs:
  - employer: LSE
    url: http://lse.ac.uk
    title: "Grad student"
    description: Top economics school in the world.

  - employer: Legislative Assembly Office 
    url: http://www.assembly.ab.ca/
    title: Policy & Research Analyst
    description: The administrative branch of the Legislative Assembly of Alberta.

  - employer: University of Alberta
    url: http://www.ualberta.ca/~cfrei
    title: Research Assistant
    description: "Studied the prisoner's dilemma in continuous time, a problem from game theory."


# External services
about_url: "http://finbarr.ca/about/"
github_url: "https://github.com/timbers"
twitter_url: "https://twitter.com/finbarrtimbers"
linkedin_url: "http://www.linkedin.com/profile/view?id=129265392"
email: "ft+site@finbarr.ca"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /:title/
relative_permalinks: false
pygments: true
