name: Finbarr Timbers
description: Personal website for Finbarr Timbers
url: "https://finbarr.ca"


# Author info
author_name: Finbarr Timbers
author_image_path: /images/finbarr-and-candace.jpg
bio: |
    I live in Alberta and used to work at [DeepMind](https://www.deepmind.com/). I previously studied at the LSE and the University of Alberta.

    I read (a lot) and discuss the books I've [read](/reading).

    You can contact me by email at finbarr [no space] timbers [at] Google's email service.


# Projects
projects:
 -

# External services
about_url: "http://finbarr.ca/about/"
github_url: "https://github.com/finbarrtimbers"
twitter_url: "https://twitter.com/finbarrtimbers"
email: "finbarrtimbers@gmail.com"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /:title/
relative_permalinks: false

videos:
  - title: "What do you like to do with mama?"
    youtube_id: "6brL0x9h6kc"
    description: "Read books. Skinnamarinky dinky dink."
  - title: "What makes mama laugh?"
    youtube_id: "wo3vX4zSiSM"
    description: "Pancakes. I like to eat them."
  - title: "What is your favourite recipe that mama cooks for you?"
    youtube_id: "Y-hq7Xazy6I"
    description: "Pancakes. I just want to eat them... and DROP THEM ON THE FLOOR."
  - title: "When you're feeling sad, what does Mama do to make you feel happy?"
    youtube_id: "ZfsSTe_Lkxs"
    description: ".... Pancakes!"
  - title: "What's your favourite song for Mama to sing for you?"
    youtube_id: "JQhye-2-ugQ"
    description: "Jupiter Saturn. Mercury and Venus, those are the big ones."
  - title: "What's your favourite song for Mama to sing for you?"
    youtube_id: "JQhye-2-ugQ"
    description: "Jupiter Saturn. Mercury and Venus, those are the big ones."
  - title: "What is your favourite game to play with Mama?""
    youtube_id: "dOshdK3QXaU"
    description: "BASKETBALL! Bonk bonk bonk bonk like this!"