name: Finbarr Timbers
description: Personal website for Finbarr Timbers
url: "http://finbarr.ca"

# Author info
author_name: Finbarr Timbers
author_image_path: /images/finbarr-and-candace.jpg
author_bio: |
    Undergrad at <a href=http://www.ualberta.ca/>UAlberta</a>. <a href=https://www.dropbox.com/s/2v7fcspgj4qsbri/cv.pdf/>CV</a>. Former NSERC USRA in mathematical finance. More <a href=/about/>about me</a>.
    

# External services
github_url: "https://github.com/timbers"
twitter_url: "https://twitter.com/finbarrtimbers"
linkedin_url: "https://linkedin.com/in/timbers"
email: "finbarr@finbarr.ca"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /:title/
relative_permalinks: false
pygments: true
